name: Deploy Infra + React App

on:
  push:
    branches: [ main ]
    paths:
      - "infra/**"
      - "app/**"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1


    # Pass Cognito values to the frontend job
    outputs:
      cognito_domain: ${{ steps.tf_outputs.outputs.cognito_domain }}
      cognito_client_id: ${{ steps.tf_outputs.outputs.cognito_client_id }}
      cognito_redirect_uri: ${{ steps.tf_outputs.outputs.cognito_redirect_uri }}
      cognito_logout_redirect_uri: ${{ steps.tf_outputs.outputs.cognito_logout_redirect_uri }}
      cognito_region: ${{ steps.tf_outputs.outputs.cognito_region }}
      cognito_scopes: ${{ steps.tf_outputs.outputs.cognito_scopes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Terraform role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::727588137294:role/github-oidc-terraform-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Export Terraform outputs
        id: tf_outputs
        working-directory: infra
        run: |
          terraform output -json > tf-outputs.json

          echo "cognito_domain=$(jq -r '.cognito_domain.value' tf-outputs.json)" >> $GITHUB_OUTPUT
          echo "cognito_client_id=$(jq -r '.cognito_client_id.value' tf-outputs.json)" >> $GITHUB_OUTPUT
          echo "cognito_redirect_uri=$(jq -r '.cognito_redirect_uri.value' tf-outputs.json)" >> $GITHUB_OUTPUT
          echo "cognito_logout_redirect_uri=$(jq -r '.cognito_logout_redirect_uri.value' tf-outputs.json)" >> $GITHUB_OUTPUT
          echo "cognito_region=$(jq -r '.cognito_region.value' tf-outputs.json)" >> $GITHUB_OUTPUT
          echo "cognito_scopes=$(jq -r '.cognito_scopes.value' tf-outputs.json)" >> $GITHUB_OUTPUT
          echo "frontend_s3_bucket=$(jq -r '.frontend_s3_bucket.value' tf-outputs.json)" >> $GITHUB_OUTPUT
          echo "frontend_cloudfront_id=$(jq -r '.frontend_cloudfront_id.value' tf-outputs.json)" >> $GITHUB_OUTPUT


frontend:
    runs-on: ubuntu-latest
    needs: terraform

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: ${{ needs.terraform.outputs.frontend_s3_bucket }}
      CLOUDFRONT_DIST_ID: ${{ needs.terraform.outputs.frontend_cloudfront_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Frontend role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::727588137294:role/github-oidc-frontend-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Build React app
        working-directory: app
        env:
          REACT_APP_COGNITO_DOMAIN: ${{ needs.terraform.outputs.cognito_domain }}
          REACT_APP_COGNITO_CLIENT_ID: ${{ needs.terraform.outputs.cognito_client_id }}
          REACT_APP_COGNITO_REDIRECT_URI: ${{ needs.terraform.outputs.cognito_redirect_uri }}
          REACT_APP_COGNITO_LOGOUT_REDIRECT_URI: ${{ needs.terraform.outputs.cognito_logout_redirect_uri }}
          REACT_APP_COGNITO_REGION: ${{ needs.terraform.outputs.cognito_region }}
          REACT_APP_COGNITO_SCOPES: ${{ needs.terraform.outputs.cognito_scopes }}
        run: npm run build

      - name: Upload to S3
        run: aws s3 sync app/build/ s3://$S3_BUCKET --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DIST_ID \
            --paths "/*"
